apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hex-encoder-fastapi-hpa
spec:
  # The deployment to target for scaling
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # This must match the name of the new deployment
    name: hex-encoder-fastapi-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
